# # query params
# http://localhost:3000/actors?id=8

# ###
# #segment params
# http://localhost:3000/actors/7

# ###
# #body params
# POST http://localhost:3000/actors
# Content-Type: application/json

# {
#   "id": 6
# }

# Movies
### index
http://localhost:3000/movies

### show
http://localhost:3000/movies/1

### create
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Lock, Stock and Two Smoking Barrels",
  "year": 1998,
  "plot": "In London, long-time friends and small-time criminals Eddie, Tom, Soap, and Bacon put together £100,000 so that Eddie, a genius card sharp, can buy into one of..."
}

### update
PATCH http://localhost:3000/movies/1
Content-Type: application/json

{
  "title": "Snatch",
  "year": 2000,
  "plot": "After stealing an 86-carat (17.2 g) diamond while dressed as an ultra-Orthodox Jew during a heist in Antwerp..."
}

### delete
DELETE http://localhost:3000/movies/11


# Actors
### index
http://localhost:3000/actors

### show
http://localhost:3000/actors/12

### create
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Nick",
  "last_name": "Moran",
  "known_for": "Eddie"
}

### update
PATCH http://localhost:3000/actors/11
Content-Type: application/json

{
  "first_name": "Jason",
  "last_name": "Flemyng",
  "known_for": "Tom"
}

### delete
DELETE http://localhost:3000/actors/9

### update
PATCH http://localhost:3000/movies/1
Content-Type: application/json

{
  "year": 1500
}

#  must have .json
### test serializer
http://localhost:3000/actors.json

###
http://localhost:3000/actors/11.json

###
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Nick",
  "last_name": "Moran",
  "known_for": "Eddie",
  "age": 30,
  "gender": "Male",
  "movie_id": 4
}

###
PATCH http://localhost:3000/actors/13
Content-Type: application/json

{
  "first_name": "Nn",
  "last_name": "Mm",
  "known_for": "Ee",
  "age": 14,
  "gender": "M",
  "movie_id": 1
}


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@admin.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "em@il.com",
  "password": "password"
}